name: Build and Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Устанавливаем JDK 17
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # 3. Даем права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Настраиваем Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # 5. Сборка проекта с Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 6. Устанавливаем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Логин в GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 8. Сборка и публикация Docker-образа
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/eureka:${{ github.run_number }}